In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris = load_iris()

In [4]:
print(iris.DESCR)

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
                
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)
    ============== ==== ==== ======= ===== ===========

In [5]:
X= iris.data

In [6]:
y = iris.target

In [8]:
from keras.utils import to_categorical

In [9]:
y = to_categorical(y)

In [10]:
from sklearn.model_selection import train_test_split

In [14]:
 X_train,X_test, y_train, y_test= train_test_split(X,y,test_size= 0.3) 

In [15]:
y_test

array([[1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [17]:
sc= MinMaxScaler()

In [18]:
sc.fit(X_train)

MinMaxScaler()

In [19]:
scaled_X_train = sc.transform(X_train)

In [35]:
scaled_X_test= sc.transform(X_test)

In [22]:
from keras.models import Sequential
from keras.layers import Dense

In [23]:
model = Sequential()
model.add(Dense(8, input_dim=4, activation ='relu'))
model.add(Dense(8, input_dim=4, activation ='relu'))
model.add(Dense(3, activation ='softmax'))
model.compile(loss='categorical_crossentropy', optimizer= 'adam', metrics= ['accuracy'])

In [24]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 8)                 40        
                                                                 
 dense_1 (Dense)             (None, 8)                 72        
                                                                 
 dense_2 (Dense)             (None, 3)                 27        
                                                                 
Total params: 139
Trainable params: 139
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.fit(scaled_X_train, y_train, epochs = 150, verbose = 2)

Epoch 1/150
4/4 - 0s - loss: 1.0916 - accuracy: 0.3048 - 10ms/epoch - 2ms/step
Epoch 2/150
4/4 - 0s - loss: 1.0894 - accuracy: 0.3048 - 11ms/epoch - 3ms/step
Epoch 3/150
4/4 - 0s - loss: 1.0875 - accuracy: 0.3048 - 9ms/epoch - 2ms/step
Epoch 4/150
4/4 - 0s - loss: 1.0860 - accuracy: 0.3048 - 9ms/epoch - 2ms/step
Epoch 5/150
4/4 - 0s - loss: 1.0847 - accuracy: 0.3048 - 10ms/epoch - 3ms/step
Epoch 6/150
4/4 - 0s - loss: 1.0834 - accuracy: 0.3524 - 11ms/epoch - 3ms/step
Epoch 7/150
4/4 - 0s - loss: 1.0818 - accuracy: 0.4762 - 11ms/epoch - 3ms/step
Epoch 8/150
4/4 - 0s - loss: 1.0804 - accuracy: 0.5429 - 12ms/epoch - 3ms/step
Epoch 9/150
4/4 - 0s - loss: 1.0789 - accuracy: 0.6381 - 9ms/epoch - 2ms/step
Epoch 10/150
4/4 - 0s - loss: 1.0774 - accuracy: 0.6571 - 10ms/epoch - 3ms/step
Epoch 11/150
4/4 - 0s - loss: 1.0757 - accuracy: 0.6571 - 9ms/epoch - 2ms/step
Epoch 12/150
4/4 - 0s - loss: 1.0741 - accuracy: 0.6571 - 10ms/epoch - 2ms/step
Epoch 13/150
4/4 - 0s - loss: 1.0724 - accuracy: 0.65

In [39]:
predictions = (model.predict(scaled_X_test)>0.5).astype('int32')

2/2 [==============================] - 0s 4ms/step


In [46]:
 y_test.argmax(axis=1)

array([0, 0, 2, 2, 2, 2, 0, 1, 0, 1, 0, 2, 2, 1, 2, 1, 1, 1, 2, 1, 0, 2,
       0, 0, 1, 1, 2, 0, 2, 2, 2, 2, 0, 2, 2, 1, 1, 2, 0, 2, 0, 0, 1, 1,
       1])

In [41]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

In [48]:
predictions

array([[1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [0, 0, 1],
       [1, 0, 0],
       [1, 0, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 0]], dtype=int32)

In [50]:
print(classification_report(y_test.argmax(axis=1),predictions))

ValueError: ignored